/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        night: '#0A0A0A',
        carbon: '#141414',
        steel: '#1E1E1E',
        chrome: '#3C3C3C',
        'bmw-blue': '#1C69D4',
        'bmw-blue-dark': '#004494',
        electric: '#2B8FFF',
        gold: '#C9A84C',
        pearl: '#EAEAEA',
        mist: '#9CA3AF',
        "background": "#0A0A0A",
        "surface": "#131313",
        "on-tertiary-container": "#4f3d00",
        "surface-variant": "#353534",
        "on-secondary-container": "#002a55",
        "surface-container-highest": "#353534",
        "surface-container-low": "#1c1b1b",
        "on-error-container": "#ffdad6",
        "tertiary": "#C9A84C",
        "outline-variant": "#424753",
        "on-surface": "#e5e2e1",
        "on-secondary-fixed": "#001b3c",
        "secondary-fixed-dim": "#a7c8ff",
        "on-tertiary": "#3d2e00",
        "primary-fixed-dim": "#adc6ff",
        "primary": "#1C69D4",
        "on-background": "#e5e2e1",
        "on-error": "#690005",
        "on-secondary-fixed-variant": "#004788",
        "primary-fixed": "#d8e2ff",
        "inverse-on-surface": "#313030",
        "primary-container": "#1c69d4",
        "secondary-fixed": "#d5e3ff",
        "tertiary-container": "#c8a74b",
        "secondary-container": "#3291ff",
        "tertiary-fixed": "#ffe08f",
        "surface-container-high": "#2a2a2a",
        "error": "#ffb4ab",
        "on-primary-fixed-variant": "#004494",
        "outline": "#8c909f",
        "on-primary-fixed": "#001a41",
        "tertiary-fixed-dim": "#e6c364",
        "surface-container": "#201f1f",
        "surface-dim": "#131313",
        "surface-tint": "#adc6ff",
        "on-tertiary-fixed": "#241a00",
        "on-secondary": "#003061",
        "secondary": "#a7c8ff",
        "on-surface-variant": "#c2c6d5",
        "on-primary": "#002e69",
        "on-primary-container": "#ebefff",
        "surface-container-lowest": "#0e0e0e",
        "on-tertiary-fixed-variant": "#584400",
        "error-container": "#93000a",
        "inverse-surface": "#e5e2e1",
        "surface-bright": "#3a3939",
        "inverse-primary": "#005bc1"
      },
      fontFamily: {
        display: ['"Inter"', 'sans-serif'], 
        sans: ['"IBM Plex Sans"', 'sans-serif'],    
        mono: ['"IBM Plex Mono"', 'monospace'], 
        headline: ['"Inter"', 'sans-serif'],
        body: ['"IBM Plex Sans"', 'sans-serif'],
        label: ['"Space Grotesk"', 'sans-serif']
      },
      borderRadius: {
        'precise': '4px', 
      },
      opacity: {
        'ghost': '0.06',
        'ghost-dark': '0.04'
      }
    },
  },
  plugins: [],
}
